#+TITLE: Informativa sulla Privacy e Cookies
#+DATE: 2015-07-21

#+MACRO: REFERENCE_NAME Pico de Paperis
#+MACRO: REFERENCE_NAME_REF Pico de Paperis
#+MACRO: REFERENCE_ADDRESS Pico de Paperis, via del campo 9, Paperopoli
#+MACRO: REFERENCE_EMAIL pico@paperopoli.com
#+MACRO: REFERENCE_WEBSITE http://picodepaperis.com
#+MACRO: REFERENCE_WEBSITE_TITLE Pico de Paperis

#+AUTHOR: Pico de Paperis
#+EMAIL: pico@paperopoli.com

#+SUB_AUTHOR: Massimo Maria Ghisalberti

#+STARTUP: showall 
#+OPTIONS: fnadjust, ^:{}
#+OPTIONS: H:6 num:6 toc:6
#+DESCRIPTION: Informativa sulla privacy, cookies e trattatamento dati personali.
#+KEYWORDS: privacy,informativa,cookies
#+LANGUAGE: it

# -HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="./org.css" />

#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="./org-toggle.css" />
#+HTML_HEAD: <script async type='text/javascript' src='./sidebar-toggle.js'></script>
#+HTML_HEAD: <meta name=viewport content="width=device-width, initial-scale=1">

#+LATEX_CLASS: nissl-org-article
#+LATEX_CLASS_OPTIONS: [a4paper]

#+LATEX_HEADER:\fancypagestyle{plain}{
#+LATEX_HEADER:  \fancyhf{} 
#+LATEX_HEADER:  \renewcommand{\headrulewidth}{0pt}
#+LATEX_HEADER:  \renewcommand{\footrulewidth}{0.4pt}
#+LATEX_HEADER:}

#+LATEX_HEADER:\fancypagestyle{fancyplain}{
#+LATEX_HEADER:  \renewcommand{\footrulewidth}{0.4pt}
#+LATEX_HEADER:}

#+LATEX_HEADER:\pagestyle{fancyplain}
#+LATEX_HEADER:\usemintedstyle{tango}

* Informativa sulla Privacy

In ottemperanza agli obblighi previsti dal *D.lgs. n. 196/2003*, altresì detto *Codice della Privacy*, con il presente testo intendiamo fornire una completa informativa ex. art. 13 del predetto Codice. \\

L'informativa si ispira anche alla *Raccomandazione n. 2/2001* che le autorità europee per la protezione dei dati personali, riunite nel *Gruppo per la tutela delle persone con riguardo al trattamento dei dati personali*, hanno istituito con l'*art. 29 della direttiva n. 95/46/CE* e che hanno adottato il *17 maggio 2001* (http://www.privacy.it/grupriracc200102.html). Qui sono stati individuati alcuni requisiti minimi per la raccolta di dati personali online; in particolare le modalità, i tempi e la natura delle informazioni che il /Titolare/ deve fornire ai /Visitatori/ quando questi si collegano a pagine web, indipendentemente dagli scopi del collegamento. \\

Pertanto informiamo l'utente che *{{{REFERENCE_NAME}}}* in qualità di /titolare/ del trattamento dei dati personali e legittimo proprietario del sito web *{{{REFERENCE_WEBSITE_TITLE}}}* reperibile all'indirizzo: {{{REFERENCE_WEBSITE}}}, sottoporrà a /trattamento adeguato/ tutti i dati di origine /personale/ che potranno pervenire o che sono già pervenuti in maniera diretta od indiretta.

** Come vengono raccolte le informazioni personali.

*** Modalità indiretta.

Alcune informazioni vengono raccolte in maniera indiretta durante la navigazione e sono conseguenza del normale funzionamento del sistema e del protocollo di /comunicazione internet/ che viene utilizzato. Queste informazioni non sono raccolte per usi specifici di identificazione e profilazione dell'utenza del sistema e quindi non sono associati direttamente all'utente. È anche vero che con opportune analisi dei dati con incroci provenienti da altre fonti terze si possa in qualche maniera risalire ed identificare l'utenza. Questi dati riguardano l'immagazzinamento in appositi file di /log/ da parte del /web server/ o della applicazione dell'/indirizzo IP/, del browser, dell'indirizzo internet richiesto (URL), del Sistema Operativo, dell'Internet Service Provider, degli URL in ingresso ed uscita, della data e ora di accesso.
 
Questi dati sono utilizzati anonimamente per fini statistici e/o storici, solamente per il livello di quantità degli accessi ed hanno una vita media di pochi giorni.

Questi dati saranno anche utilizzati in caso di attività illecite o qualsiasi tentativo di reato informatico contro: {{{REFERENCE_NAME}}} o il sito {{{REFERENCE_WEBSITE}}}; in tal caso saranno forniti alle autorità competenti in materia. 
Il sito {{{REFERENCE_WEBSITE}}} utilizza (o potrebbe utilizzare in futuro) inoltre il servizio /Google Analytics/ fornito da *Google Inc. (Google)*. Google elabora i dati personali provenienti dal sito web {{{REFERENCE_WEBSITE}}} allo scopo di esaminare ed elaborarne le statistiche di accesso. Google potrebbe utilizzare questi dati per una sua profilazione propria da usare sui propri network che va oltre ogni nostra conoscenza e non imputabile a *{{{REFERENCE_NAME}}}*.

Per conoscere le regole di /privacy/ di Google: http://www.google.com/intl/it/policies/privacy/.
Per impedire a Google Analytics di raccogliere i dati: https://tools.google.com/dlpage/gaoptout?hl=it%5D%28tools.google.com/dlpage/gaoptout?hl=it.

Per impedire ad una vasta serie di /tracker/ consigliamo: https://www.eff.org/privacybadger.
Per rendersi conto di quanto si possa essere tracciabili: https://panopticlick.eff.org/.

*** Modalità diretta.

Nel caso in cui dei dati siano indispensabili per poter usufruire di servizi diretti forniti da *{{{REFERENCE_NAME}}}*, ne sarà indicata specificatamente la finalità e fornito un modo semplificato per la loro rimozione tramite una procedura adeguata o una semplice richiesta via email a {{{REFERENCE_EMAIL}}}. 

* Cookies

I *cookies* (https://it.wikipedia.org/wiki/Cookie) sono dei piccoli file di testo che immagazzinano porzioni di informazioni. Sono salvati sul computer dell'utente dal browser su richiesta del sito web. Possono contenere pochi dati ed hanno in genere un intervallo di durabilità: permanente o temporanea.
Possono essere del dominio visitato ma anche di terzi.
Sono tipicamente utilizzati per permettere, ad esempio, il /login/ all'interno di parti private dei siti web e per non chiedere continuamente le credenziali ad ogni cambio di pagina. 
È una forma per consentire ad un sito web di avere un minimo di impostazione personalizzata.
Il supporto per i /cookies/ è facilmente disabilitabile dalle impostazione del browser in uso, ma la loro inibizione potrebbe pregiudicare il corretto funzionamento di un sito web.
Possono essere eliminati facilmente cancellando la /cronologia/ completa del browser in qualsiasi momento.

**** Cookies tecnici

Ricadono nei /cookie tecnici/ i caratteristici /cookie di sessione/ citati prima e non è prevista segnalazione del loro utilizzo.

**** Cookie di profilazione

I cookie di profilazione, in base alla legge vigente, devono essere segnalati e deve essere lasciata all'utente la scelta se accettarli o no.
Il sito {{{REFERENCE_WEBSITE}}} non usa cookies di profilazione diretta (è usato Google Analytics in modalità *IP anonimo*).

**** Cookie analitici

Si tratta di cookie utilizzati per analisi statistiche. Questo tipo di cookie raccoglie informazioni in forma anonima sull'attività degli utenti nel sito. Questo tipo di cookie viene erogato esclusivamente da terze parti: Google Analytics che è stato configurato per anonimizzare l'indirizzo IP.

Il consenso all'utilizzo dei cookie viene prestato inizialmente attraverso le seguenti modalità: chiudendo il banner, scorrendo la pagina che ospita il banner o cliccando qualunque suo elemento.

Opzioni circa l'uso dei cookie da parte del sito mediante le impostazione del browser.

L'erogazione di tutti i cookie, sia di prime che di terze parti, è disattivabile intervenendo sulle impostazioni del browser in uso; è bene notare però che questo potrebbe rendere inutilizzabili i siti qualora si bloccassero i cookie indispensabili per l'erogazione delle funzionalità. Ogni browser dispone di impostazioni diverse per la disattivazione dei cookie; di seguito proponiamo i collegamenti alle istruzioni per i browser più comuni. 

+ [[http://windows.microsoft.com/it-it/windows7/block-enable-or-allow-cookies][Microsoft Internet Explorer]]
+ [[https://support.google.com/accounts/answer/61416?hl=it][Google Chrome]]
+ [[https://support.apple.com/kb/PH19214?locale=it_IT][Apple Safari]]
+ [[https://support.mozilla.org/it/kb/Attivare%20e%20disattivare%20i%20cookie][Mozilla Firefox]]
+ [[http://help.opera.com/Windows/10.00/it/cookies.html][Opera]]


* Collegamenti verso altri siti web

Il sito web {{{REFERENCE_WEBSITE}}} presenta collegamenti verso altri siti web di soggetti terzi.
La *{{{REFERENCE_NAME}}}* declina ogni più completa responsabilità in merito all'utilizzo che questi soggetti possano fare dei dati in loro possesso e non accetterà in nessun caso incarico di intermediazione tra l'utente ed i terzi in questione.

* Dichiarazione

*{{{REFERENCE_NAME}}}* dichiara che il /trattamento dei dati personali/ acquisiti con le modalità sopra descritte sarà nel pieno rispetto delle norme del Codice della Privacy e dei principi di /correttezza/, /liceità/, /trasparenza/,/pertinenza/, /completezza/ e /non eccedenza/ (ex art. 11 del Codice della Privacy). Inoltre i suddetti dati saranno raccolti e registrati solamente per le finalità di a seguire e conservati per un periodo strettamente necessario agli scopi. 

I tipi di dati raccolti sono:

- /Obbligatori/, per il raggiungimento delle finalità connesse agli obblighi di leggi, regolamenti o normative comunitarie.
- /Facoltativi/, ma necessari per lo svolgimento e la fuizione del Servizio fornito da *{{{REFERENCE_NAME}}}* direttamente o tramite il sito web {{{REFERENCE_WEBSITE}}}. 

I dati /facoltativi/ eventualmente e legittimamente rifiutati, potrebbero portare a delle difficoltà nella gestione ed erogazione del Servizio da parte di *{{{REFERENCE_NAME}}}*.

Pertanto secondo quanto previsto dall'articolo /13 del Codice della Privacy/, informiamo che i dati saranno trattati per le seguenti finalità: 

- Gestione e registrazione al sito {{{REFERENCE_WEBSITE}}}
- Offerta di eventuali servizi personalizzati.
- Adempiere a qualunque obbligo legale previsto per legge, regolamento o normativa comunitaria.
- Eventuale invio di newsletter, email o altra comunicazione relativa al servizio fornito da *{{{REFERENCE_NAME}}}*.

Il trattamento sarà effettuato con le seguenti modalità:

- Il responsabile del trattamento (Titolare) è: *{{{REFERENCE_NAME}}}* nella figura di /{{{REFERENCE_NAME_REF}}}/.

- Il trattamento potrà consistere nella raccolta, registrazione, organizzazione, conservazione, consultazione, elaborazione, modificazione, selezione, estrazione, comparazione, raffronto, utilizzo, interconnessione, blocco, cancellazione e distruzione dei dati; potrà essere effettuato con mezzi informatici, telematici e/o cartacei idonei a garantire la sicurezza e la riservatezza degli stessi in linea a quanto previsto dall'*art. 31 del D.Lgs 196/2003* relativo alle /misure minime di sicurezza per il trattamento dei dati personali/.

- I dati sono raccolti presso la sede del Titolare o archiviati in Paesi appartenenti all'Unione Europea con leggi equivalenti in merito alla adeguata tutela dei dati personali.

- I dati personali direttamente riferibili all'utente non saranno forniti in nessun caso a soggetti terzi se non dietro previa autorizzazione dello stesso o ingiunzioni legali da parte degli organi di pubblica sicurezza.

- Nell'effettuare il trattamento saranno adottate tutte le misure organizzative e tecniche in grado di garantire almeno il levello minimo di sicurezza come da *Allegato B del D.Lgs 196/03*.

- I dati potranno essere comunicati a Enti Pubblici, Forze di Polizia o altri Soggetti Pubblici e Privati, ma esclusivamente al fine di adempiere ad obblighi di legge, regolamento o normativa comunitaria.

- I dati saranno cancellati su richiesta dell'utente in qualsiasi momento.

- I dati potranno essere richiesti dall'utente, se ancora in possesso a *{{{REFERENCE_NAME}}}*, dietro comunicazione e richiesta scritta o tramite email. 


Ogni richiesta o delucidazione potrà pervenire via email a {{{REFERENCE_EMAIL}}} o se presente a questo indirizzo in forma scritta: *{{{REFERENCE_ADDRESS}}}*.


